Repository docker-mailserver/docker-mailserver-new, pull requests merged in 2021-01, with the labels that each got.

#11 Fixes the PR testing problems
  .github/workflows/close_stale_issues.yml
  .github/workflows/default_on_push.yml
  .github/workflows/linting.yml
  .github/workflows/scheduled_builds.yml
  .github/workflows/test_merge_requests.yml
  README.md
Labels: area/ci, kind/bug, meta/needs triage, meta/wip, pr/needs review, priority/high

#13 Add init system
  Dockerfile
Labels: area/enhancement, kind/feature request, pr/can be merged, priority/medium

#10 Solve Fetchmail imap idle issue
  ENVIRONMENT.md
  target/bin/fetchmailrc_split
  target/scripts/start-mailserver.sh
  test/config/fetchmail.cf
  test/mail_fetchmail_parallel.bats
Labels: area/enhancement, pr/can be merged, priority/medium

#14 feat: leverage cache to prevent unnecessary pushing and building
  .github/workflows/default_on_push.yml
  .github/workflows/test_merge_requests.yml
Labels: area/ci, area/enhancement, kind/configuration, pr/can be merged, pr/needs review, priority/high

#16 Add dependabot for github actions and git submodules
  .github/dependabot.yml
Labels: area/ci, area/enhancement, pr/can be merged

#18 Introducing the repository secret
  .editorconfig
  .github/workflows/close_stale_issues.yml
  .github/workflows/default_on_push.yml
  .github/workflows/scheduled_builds.yml
  Dockerfile
  Makefile
  setup.sh
  test/test_helper/common.bash
Labels: area/ci, area/enhancement, kind/configuration, pr/can be merged, priority/low
